<?php
/** Auto-generated by Craftable PRO */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ClubPage extends Model {


    protected $table = 'club_page';
    protected $fillable = ['title', 'content', 'slug', 'published_at', 'craftable_pro_users_id', 'club_id'];


protected $casts = [
    ];
}