<?php
/** Auto-generated by Craftable PRO */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class InfoUser extends Model {


    protected $table = 'info_users';
    protected $fillable = ['gender', 'department', 'year', 'phone', 'craftable_pro_users_id'];


protected $casts = [
    ];
}