<?php
/** Auto-generated by Craftable PRO */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SubRole extends Model {


    protected $table = 'sub_role';
    protected $fillable = ['name'];


protected $casts = [
    ];
}