<?php
/** Auto-generated by Craftable PRO */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class RoleClub extends Model {


    protected $table = 'role_club';
    protected $fillable = ['info_users_id', 'club_id', 'sub_role_id'];

    public function infoUser(): BelongsTo
    {
        return $this->belongsTo(\App\Models\InfoUser::class, 'info_users_id', 'id');
    }


    public function club(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Club::class, 'club_id', 'id');
    }


    public function subRole(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SubRole::class, 'sub_role_id', 'id');
    }


protected $casts = [
    ];
}